In [2]:
import numpy as np

A = np.array([[1, 4, 7, -2], [3, 0, -2, -1], [-4, 2, 1, 0], [-8, -3, -1, 2]])
print(A)

p1 = np.array([[0, 0, 1, 0], [0, 1, 0, 0], [1, 0, 0, 0], [0, 0, 0, 1]])
p2 = np.array([[0, 0, 1, 0], [0, 1, 0, 0], [0, 0, 0, 1], [1, 0, 0, 0]])
p3 = np.eye(4)
p4 = np.array([[0, 0, 0, 1], [0, 1, 0, 0], [1, 0, 0, 0], [0, 0, 1, 0]])
print(p1)
print(p2)
print(p3)
print(p4)

[[ 1  4  7 -2]
 [ 3  0 -2 -1]
 [-4  2  1  0]
 [-8 -3 -1  2]]
[[0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 0 1]]
[[0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]
 [1 0 0 0]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0 0 0 1]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]]


In [10]:
print("Solution: ")
s1 = A@p1
s2 = A@p2
s3 = A@p3
s4 = A@p4
print(s1)
print(s2)
print(s3)
print(s4)

Solution: 
[[ 7  4  1 -2]
 [-2  0  3 -1]
 [ 1  2 -4  0]
 [-1 -3 -8  2]]
[[-2  4  1  7]
 [-1  0  3 -2]
 [ 0  2 -4  1]
 [ 2 -3 -8 -1]]
[[ 1.  4.  7. -2.]
 [ 3.  0. -2. -1.]
 [-4.  2.  1.  0.]
 [-8. -3. -1.  2.]]
[[ 7  4 -2  1]
 [-2  0 -1  3]
 [ 1  2  0 -4]
 [-1 -3  2 -8]]


In [11]:
print("Solution: ")
s1 = p1@A
s2 = p2@A
s3 = p3@A
s4 = p4@A
print(s1)
print(s2)
print(s3)
print(s4)

Solution: 
[[-4  2  1  0]
 [ 3  0 -2 -1]
 [ 1  4  7 -2]
 [-8 -3 -1  2]]
[[-4  2  1  0]
 [ 3  0 -2 -1]
 [-8 -3 -1  2]
 [ 1  4  7 -2]]
[[ 1.  4.  7. -2.]
 [ 3.  0. -2. -1.]
 [-4.  2.  1.  0.]
 [-8. -3. -1.  2.]]
[[-8 -3 -1  2]
 [ 3  0 -2 -1]
 [ 1  4  7 -2]
 [-4  2  1  0]]


In [20]:
A1 = np.array([[2, 3, 4], [-2, -2, -2], [0, 1, 0], [-1, -3, -2]])
A2 = np.array([[-1, -2, -1], [2, 1, -2], [3, 0, -3]])
v = np.array([1, 2, 3])
print((A1@A2@v).shape)

(4,)


In [23]:
A = np.array([[2, -3, 1], [3, 1, 1], [-1, -2, -1]])
b = np.array([2, -1, 1])
print(np.linalg.solve(A, b))

[-0.33333333 -0.66666667  0.66666667]


In [24]:
A1 = np.array([[2, 3], [-2, 0]])
A2 = np.array([[1, -2], [3, 1]])
print(4 * A1 - A2)

[[  7  14]
 [-11  -1]]


In [25]:
A1 = np.array([[2, -3, 1], [-2, -1, 4], [0, 2, 2]])
A2 = np.array([[3, -2, 1], [1, -1, 2], [-2, 2, 0]])
print(A1@A2)

[[  1   1  -4]
 [-15  13  -4]
 [ -2   2   4]]


In [26]:
matrix = np.array([[3, 2, 4], [-1, 0, 2], [3, -2, 8]])
inv = np.linalg.inv(matrix)
print(inv)

[[ 0.08333333 -0.5         0.08333333]
 [ 0.29166667  0.25       -0.20833333]
 [ 0.04166667  0.25        0.04166667]]


In [29]:
import math

v1 = np.array([3, -1, 2])
v2 = np.array([0, -1, 1])
theta = math.degrees(np.arccos(
    (v1@v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))
))
print(str(theta) + "\"")

55.46241621381916"


In [31]:
print(np.linalg.norm([-2, -3, 0, 5, 1]))

6.244997998398398


In [7]:
A1 = np.array([[1, 2, 3], [4, 0, 1]])
A2 = np.array([[1, 1, 0], [0, 1, 1], [1, 0, 1]])
# result = A1 * A2
print(A1)
print(A2)
print(A1@A2)

[[1 2 3]
 [4 0 1]]
[[1 1 0]
 [0 1 1]
 [1 0 1]]
[[4 3 5]
 [5 4 1]]


In [8]:
A1 = np.array([[2, 4, 5, 6]])
A2 = np.array([[1], [3], [2], [1]])
print(A1@A2)

[[30]]


In [13]:
A = np.array([[1, 0, 1/3], [0, 1, -1/4]])
r = np.array([[6], [2], [3]])
print(A@r)
R = np.array([[5, -1, -3, 7], [4, -4, 1, -2], [9, 3, 0, 12]])
print(A@R)

[[7.  ]
 [1.25]]
[[ 8.    0.   -3.   11.  ]
 [ 1.75 -4.75  1.   -5.  ]]
