In [2]:
import numpy as np

A = np.array([[1, 4, 7, -2], [3, 0, -2, -1], [-4, 2, 1, 0], [-8, -3, -1, 2]])
print(A)

p1 = np.array([[0, 0, 1, 0], [0, 1, 0, 0], [1, 0, 0, 0], [0, 0, 0, 1]])
p2 = np.array([[0, 0, 1, 0], [0, 1, 0, 0], [0, 0, 0, 1], [1, 0, 0, 0]])
p3 = np.eye(4)
p4 = np.array([[0, 0, 0, 1], [0, 1, 0, 0], [1, 0, 0, 0], [0, 0, 1, 0]])
print(p1)
print(p2)
print(p3)
print(p4)

[[ 1  4  7 -2]
 [ 3  0 -2 -1]
 [-4  2  1  0]
 [-8 -3 -1  2]]
[[0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 0 1]]
[[0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]
 [1 0 0 0]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0 0 0 1]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]]


In [10]:
print("Solution: ")
s1 = A@p1
s2 = A@p2
s3 = A@p3
s4 = A@p4
print(s1)
print(s2)
print(s3)
print(s4)

Solution: 
[[ 7  4  1 -2]
 [-2  0  3 -1]
 [ 1  2 -4  0]
 [-1 -3 -8  2]]
[[-2  4  1  7]
 [-1  0  3 -2]
 [ 0  2 -4  1]
 [ 2 -3 -8 -1]]
[[ 1.  4.  7. -2.]
 [ 3.  0. -2. -1.]
 [-4.  2.  1.  0.]
 [-8. -3. -1.  2.]]
[[ 7  4 -2  1]
 [-2  0 -1  3]
 [ 1  2  0 -4]
 [-1 -3  2 -8]]


In [11]:
print("Solution: ")
s1 = p1@A
s2 = p2@A
s3 = p3@A
s4 = p4@A
print(s1)
print(s2)
print(s3)
print(s4)

Solution: 
[[-4  2  1  0]
 [ 3  0 -2 -1]
 [ 1  4  7 -2]
 [-8 -3 -1  2]]
[[-4  2  1  0]
 [ 3  0 -2 -1]
 [-8 -3 -1  2]
 [ 1  4  7 -2]]
[[ 1.  4.  7. -2.]
 [ 3.  0. -2. -1.]
 [-4.  2.  1.  0.]
 [-8. -3. -1.  2.]]
[[-8 -3 -1  2]
 [ 3  0 -2 -1]
 [ 1  4  7 -2]
 [-4  2  1  0]]


In [20]:
A1 = np.array([[2, 3, 4], [-2, -2, -2], [0, 1, 0], [-1, -3, -2]])
A2 = np.array([[-1, -2, -1], [2, 1, -2], [3, 0, -3]])
v = np.array([1, 2, 3])
print((A1@A2@v).shape)

(4,)


In [23]:
A = np.array([[2, -3, 1], [3, 1, 1], [-1, -2, -1]])
b = np.array([2, -1, 1])
print(np.linalg.solve(A, b))

[-0.33333333 -0.66666667  0.66666667]


In [24]:
A1 = np.array([[2, 3], [-2, 0]])
A2 = np.array([[1, -2], [3, 1]])
print(4 * A1 - A2)

[[  7  14]
 [-11  -1]]


In [25]:
A1 = np.array([[2, -3, 1], [-2, -1, 4], [0, 2, 2]])
A2 = np.array([[3, -2, 1], [1, -1, 2], [-2, 2, 0]])
print(A1@A2)

[[  1   1  -4]
 [-15  13  -4]
 [ -2   2   4]]


In [26]:
matrix = np.array([[3, 2, 4], [-1, 0, 2], [3, -2, 8]])
inv = np.linalg.inv(matrix)
print(inv)

[[ 0.08333333 -0.5         0.08333333]
 [ 0.29166667  0.25       -0.20833333]
 [ 0.04166667  0.25        0.04166667]]


In [29]:
import math

v1 = np.array([3, -1, 2])
v2 = np.array([0, -1, 1])
theta = math.degrees(np.arccos(
    (v1@v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))
))
print(str(theta) + "\"")

55.46241621381916"


In [31]:
print(np.linalg.norm([-2, -3, 0, 5, 1]))

6.244997998398398


In [7]:
A1 = np.array([[1, 2, 3], [4, 0, 1]])
A2 = np.array([[1, 1, 0], [0, 1, 1], [1, 0, 1]])
# result = A1 * A2
print(A1)
print(A2)
print(A1@A2)

[[1 2 3]
 [4 0 1]]
[[1 1 0]
 [0 1 1]
 [1 0 1]]
[[4 3 5]
 [5 4 1]]


In [8]:
A1 = np.array([[2, 4, 5, 6]])
A2 = np.array([[1], [3], [2], [1]])
print(A1@A2)

[[30]]


In [13]:
A = np.array([[1, 0, 1/3], [0, 1, -1/4]])
r = np.array([[6], [2], [3]])
print(A@r)
R = np.array([[5, -1, -3, 7], [4, -4, 1, -2], [9, 3, 0, 12]])
print(A@R)

[[7.  ]
 [1.25]]
[[ 8.    0.   -3.   11.  ]
 [ 1.75 -4.75  1.   -5.  ]]


In [16]:
A = np.array([[1, 7, 9], [4, 2, 5], [6, 1, 3]])
v = np.array([3, 2, 8])
(x, y, z) = np.linalg.solve(A, v)
print("x = " + str(x), ", y = " + str(y), ", z = " + str(z))

x = 2.0909090909090913 , y = 3.6363636363636376 , z = -2.727272727272728


In [3]:
A = np.array([[5, 0], [0, 4]])
print(A @ A @ A)

[[125   0]
 [  0  64]]


In [1]:
import numpy as np
import numpy.linalg as LA

A = np.array([[2,1,1,1], [-1,0,-1,-1], [1,1,2,1], [-1,-1,-1,0]])
print(LA.det(A))

1.0


In [7]:
A = np.array([[-1,-1,-1,-1],[-1,-1,-1,-1],[4,3,4,2],[-2,0,-2,1]])
# A2 = np.array([[-2,-1,-1,-1],[-1,-2,-1,-1],[4,3,3,2],[-2,0,-2,-2]])
v = np.array([1,1,1,2])
print(A@v)
v = np.array([-1,-1,1,2])
print(A@v)
v = np.array([-1,0,1,0])
print(A@v)
v = np.array([1,0,1,0])
print(A@v)
print(LA.det(np.array([[1,1,0],[-3,-2,-2],[2,2,1]])))
# print(LA.inv(np.array([[2,1],[6,3]])))

[-5 -5 15 -2]
[-1 -1  1  2]
[0 0 0 0]
[-2 -2  8 -4]
1.0000000000000002


LinAlgError: Singular matrix

In [8]:
print(LA.inv(np.array([[1,-1,2],[1,0,1],[-1,-1,1]])))

[[ 1. -1. -1.]
 [-2.  3.  1.]
 [-1.  2.  1.]]


In [17]:
import numpy as np

O1 = np.array([[3,0,0],[0,0,1],[0,1,0]])
O2 = np.array([[0,1,0],[1,0,0],[0,0,4]])
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

O3 = O2@O1
print(O2@O1@A == O3@A)
print(O3)

A = np.array([[1,-3,4],[4,-7,8],[6,-7,7]])
B = np.array([[4,-5,7],[1,-4,9],[-4,0,5]])
print(A@B)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[0 0 1]
 [3 0 0]
 [0 4 0]]
[[-15   7   0]
 [-23   8   5]
 [-11  -2  14]]


In [19]:
print(LA.det(np.array([[1,-3,4],[4,-7,8],[6,-7,7]])))
print(LA.det(np.array([[4,-5,7],[1,-4,9],[-4,0,5]])))

3.000000000000009
12.99999999999999


In [20]:
A = np.array([[1, -3, 1], [2, -8, 8], [-6, 3, -15]])
v = np.array([4, -2, 9])
x, y, z = LA.solve(A, v)
print("x=" + str(x) + ", y=" + str(y), ", z=" + str(z))

x=3.0000000000000013, y=-1.0000000000000002 , z=-2.0000000000000004


In [21]:
print(LA.inv(np.array([[2, 4, -2], [-2, 0, 1], [3, -3, 0]])))

[[0.5        1.         0.66666667]
 [0.5        1.         0.33333333]
 [1.         3.         1.33333333]]


In [16]:
import numpy as np
c = np.array([[-0.5, 1, 1.5], [-0.5, 1, 2.5], [0.5, 0, -0.5]])
v = np.array([-1, -6, 3])
print("Vector with changed basis: " + str(c@v))

Vector with changed basis: [-1.  2. -2.]


In [17]:
L = np.array([[6,0,0],[0,8,0],[5,0,7]])
U = np.array([[3,0,0],[0,3,7],[0,0,2]])
print(L@U)

[[18  0  0]
 [ 0 24 56]
 [15  0 14]]
