In [4]:
# import libraries
import numpy as np

In [10]:
# append array
print(np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]]))
# print(np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis = 0))
array = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
print("linearly transform a 2D array to a 1D array:\n" + str(np.append([], array)))

[1 2 3 4 5 6 7 8 9]
linearly transform a 2D array to a 1D array
[1. 2. 3. 1. 2. 3. 1. 2. 3.]


In [17]:
a = np.array([1, 2, 3]) # summoning an array
a

array([1, 2, 3])

In [12]:
np.zeros(2) # an array of zeros

array([0., 0.])

In [13]:
np.ones(2) # an array of ones

array([1., 1.])

In [16]:
np.empty(2) # an empty array, faster

array([1., 1.])

In [19]:
np.arange(4)

array([0, 1, 2, 3])

In [20]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [21]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
x = np.ones(2, dtype=np.int64) # specifying data type
x

array([1, 1], dtype=int64)

In [29]:
X = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(X)
print(np.sort(X))

[2 1 5 3 7 4 6 8]
[1 2 3 4 5 6 7 8]


In [31]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(np.concatenate((a, b)))

[1 2 3 4 5 6 7 8]


In [35]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
print(np.concatenate((x, y), axis=0))

[[1 2]
 [3 4]
 [5 6]]


In [37]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
print("dimensions:  " + str(array_example.ndim))
print("elements:    " + str(array_example.size))
print("shape:       " + str(array_example.shape))

dimensions:  3
elements:    24
shape:       (3, 2, 4)


In [51]:
X = np.array([[1, 2, 3, 4],
              [1, 5, 3, 5],
              [1, 2, 3, 6]])
print("dimensions: " + str(X.ndim))
print("elements:   " + str(X.size))
# print("shape:      " + str(X.shape))
N, D = X.shape
print("size of D1: " + str(N) + "\nsize of D2: " + str(D))
mean = np.zeros((D,))
print(mean)
# for n in range(N):
    # print("data of " + str(n) + ": " + str(X[n]))
for d in range(D):
    mean[d] = np.sum(X[:, d]) / N # calculate the channel mean
print(mean)

dimensions: 2
elements:   12
size of D1: 3
size of D2: 4
[0. 0. 0. 0.]
[1. 3. 3. 5.]


In [73]:
def mean_naive(X):
    """Compute the sample mean for a 2D data set"""
    N, D = X.shape
    mean = np.empty((D,))
    for d in range(D):
        mean[d] = np.sum(X[:, d]) / N # calculate the channel mean
    return mean
print(mean_naive(X)) # test cell

[1. 3. 3. 5.]


In [112]:
print("input data:\n" + str(X))
N, D = X.shape
print("samples:        " + str(N) + "\ndimensionality: " + str(D))
mean = mean_naive(X)
print("sample mean:    " + str(mean))

print("mean matrix:")
a = mean
for i in range(N - 1):
    a = np.vstack((a, mean))
print(a)
print("deviation matrix (xi-mu):")
d = X-a
print(d)
print("variance matrix:")
v = (d.T@d)/N
print(v)
# covariance = np.zeros((D, D))
# print(covariance)

input data:
[[1 2 3 4]
 [1 5 3 5]
 [1 2 3 6]]
samples:        3
dimensionality: 4
sample mean:    [1. 3. 3. 5.]
mean matrix:
[[1. 3. 3. 5.]
 [1. 3. 3. 5.]
 [1. 3. 3. 5.]]
deviation matrix (xi-mu):
[[ 0. -1.  0. -1.]
 [ 0.  2.  0.  0.]
 [ 0. -1.  0.  1.]]
variance matrix:
[[0.         0.         0.         0.        ]
 [0.         2.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.66666667]]


In [119]:
def cov_naive(X):
    N, D = X.shape
    mean_v = mean_naive(X)
    mean_m = mean_v
    for i in range(N - 1):
        mean_m = np.vstack((mean_m, mean_v))
    deviation_m = X - mean_m
    variance_m = (deviation_m.T@deviation_m)/N
    return variance_m

X = np.array([[90, 60, 90],
              [90, 90, 30],
              [60, 60, 60],
              [60, 60, 90],
              [30, 30, 30]])
print(cov_naive(X))

[[504. 360. 180.]
 [360. 360.   0.]
 [180.   0. 720.]]


In [121]:
print(np.mean(X, axis=0))
print(np.cov(np.transpose(X), bias=True))

[66. 60. 60.]
[[504. 360. 180.]
 [360. 360.   0.]
 [180.   0. 720.]]


In [63]:
# D, N = X.shape # ALT
# mean = np.zeros((D, 1))
# print("size of D1: " + str(D) + "\nsize of D2: " + str(N))
# print(mean)

In [134]:
# Calculating the mean after the affine transformation
# print("input data:\n" + str(X))
mean = np.full((2,), 2)
print("mean vector: " + str(mean))
affine_m = np.zeros(mean.shape) # zero matrix of shape (D, )
# print(affine_m)

sample_A = np.array([[0, 1],
                     [2, 3]])
sample_b = np.ones(2)
print(sample_A@mean + sample_b)

mean vector: [2 2]
[ 3. 11.]


In [129]:
m = np.full((2,), 2)
print(m)

[2 2]


In [ ]:
def affine_mean(mean, A, b):
    return A@mean + b

def affine_covariance(S, A, b):
    return A@S@A.T