In [1]:
import numpy as np

# append array
np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
array = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
np.append([], array)

array([1., 2., 3., 1., 2., 3., 1., 2., 3.])