In [2]:
import numpy as np

# 4x4 identity matrix
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
# 5-element vector of zeros
zero_vector = np.zeros(5)
print(zero_vector)

[0. 0. 0. 0. 0.]


In [8]:
# 3x2 matrix of zeros
zero_matrix = np.zeros((3, 2))
print(zero_matrix)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [10]:
A = np.array([[1, 2], [3, 4]])
A_transpose = A.T # the transpose of a matrix
print(A)
print(A_transpose)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [11]:
#task 3
# Given
A = np.array([[1,-1,1], [0,1,0], [-1,2,1]])
B = np.array([[0.5,1.5,-0.5], [0,1,0], [0.5,-0.5,0.5]])

print(A@B)
print(B@A)

print(A.T)
print(B.T)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 1  0 -1]
 [-1  1  2]
 [ 1  0  1]]
[[ 0.5  0.   0.5]
 [ 1.5  1.  -0.5]
 [-0.5  0.   0.5]]


In [12]:
# additional sub-library
v = np.array([2, -4, 1])
v_norm = np.linalg.norm(v)  # magnitude
print(v_norm)

4.58257569495584


In [13]:
A = np.array([[1, 2], [3, 4]])  # inverse
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [16]:
# solve for unknown variables in a system on linear equations
#  x + 4y -  z = -1
# -x - 3y + 2z =  2
# 2x -  y - 2z = -2
# each array in A is an equation from the above system of equations
A = np.array([[1,4,-1],[-1,-3,2],[2,-1,-2]])
# the solution to each equation
b = np.array([-1,2,-2])
# solve for x, y, and z
x,y,z = np.linalg.solve(A,b)
print((x, y, z))

(0.0, 0.0, 1.0)


In [17]:
#task 4
# Represent the following system in NumPy matrix/vector form, then solve for x, y, and z

# Given
'''
4x + z = 2
-y + 2z - 3x = 0
.5y - x - 1.5z = -4
'''
A = np.array([[4, 0, 1], [-3, -1, 2], [-1, .5, -1.5]])
b = np.array([2, 0, -4])
x, y, z = np.linalg.solve(A, b)
print((x, y, z))

(6.0, -62.0, -22.0)


In [18]:
# Given
'''
2a + 3d - 2c = 4
-c + 4b - a = 1
2d - 2c + 3a - b = 2
-2a + 3c - b = -2
'''
A = np.array([[2, 0, -2, 3], [-1, 4, -1, 0], [3, -1, -2, 2], [-2, -1, 3, 0]])
b = np.array([4, 1, 2, -2])
a, b, c, d = np.linalg.solve(A, b)
print((a, b, c, d))

(-1.4999999999999998, -0.5909090909090906, -1.8636363636363633, 1.0909090909090908)
