In [1]:
import numpy as np

v = np.array([1, 2, 3, 4, 5, 6]) # creating a vector
A = np.array([[1, 2], [3, 4]]) # creating a matrix
print(v)
print(A)

[1 2 3 4 5 6]
[[1 2]
 [3 4]]


In [5]:
v = np.array([-2, -2, -2, -2])
u = np.array([0, 0, 0, 0])
w = np.array([3, 3, 3, 3])

A = np.column_stack((v, u, w))  # creating a matrix by using np.column_stack()
print(A)

[[-2  0  3]
 [-2  0  3]
 [-2  0  3]
 [-2  0  3]]


In [10]:
A = np.array([[1, 2], [3, 4]])
print(A)
print(A.shape) # accessing shape

[[1 2]
 [3 4]]
(2, 2)


In [11]:
A = np.array([[1, 2], [3, 4]])
print(A[0, 1]) # index the element

2


In [12]:
A = np.array([[1, 2], [3, 4]])
print(A[:, 1]) # index the second column and use an empty colon to select every row

[2 4]


In [14]:
#Task 1
# Given vectors
vector_1 = np.array([-2,-6,2,3])
vector_2 = np.array([4,1,-3,8])
vector_3 = np.array([5,-7,9,0])

matrix = np.column_stack((vector_1, vector_2, vector_3))
print(matrix)
print(matrix.shape) #access the matrix shape
print(matrix[:, 2]) #print the third column

[[-2  4  5]
 [-6  1 -7]
 [ 2 -3  9]
 [ 3  8  0]]
(4, 3)
[ 5 -7  9  0]


In [15]:
#multiply a matrix:
A = np.array([[1, 2], [3, 4]])
4 * A

array([[ 4,  8],
       [12, 16]])

In [16]:
#add a matrix:
A = np.array([[1, 2], [3, 4]])
B = np.array([[-4, -3], [-2, -1]])
A + B

array([[-3, -1],
       [ 1,  3]])

In [17]:
#vector dot products:
v = np.array([-1, -2, -3])
u = np.array([2, 2, 2])
np.dot(v, u)

-12

In [18]:
#matrix multiplication:
A = np.array([[1, 2], [3, 4]])
B = np.array([[-4, -3], [-2, -1]])
# one way to matrix multiply
np.matmul(A, B)
# another way to matrix multiply
A@B

array([[ -8,  -5],
       [-20, -13]])

In [3]:
import numpy as np
#task 2 (matrix multiplication)
# Given
# 2 x 3 matrix
A = np.array([[2,3,-4], [-2, 1, -3]])
# 2 x 3 matrix
B = np.array([[1,-1,4], [3,-3,3]])
# 3 x 2 matrix
C = np.array([[1, 2], [3, 4], [5, 6]])

print(B.shape[0])

# Calculate D = 4A - 2B
D = 4 * A - 2 * B
print(D)
# Calculate E = AC
E = A@C
print(E)
print(E.shape)
# Calculate F = CA
F = C@A
print(F)
print(F.shape)

2
[[  6  14 -24]
 [-14  10 -18]]
[[ -9  -8]
 [-14 -18]]
(2, 2)
[[ -2   5 -10]
 [ -2  13 -24]
 [ -2  21 -38]]
(3, 3)
